name = "my-worker"
type = "javascript"

account_id = "${CF_ACCOUNT_ID}"
workers_dev = true
kv_namespaces = [
  { binding = "FORM_DATA", id = "${KV_NAMESPACE_ID}", preview_id = "${KV_NAMESPACE_ID}" }
]

main = "./workers/worker.js"
compatibility_date = "2024-07-17"